# Generated by Django 6.1.1 on 2026-09-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='drop_chance',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
