# Generated by Django 6.1.1 on 2026-09-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='rariry',
            field=models.CharField(choices=[('common', 'Обычная'), ('rare', 'Редкая'), ('epic', 'Эпическая'), ('legendary', 'Легендарная'), ('secret', 'Секретная')], default=150, max_length=50),
            preserve_default=False,
        ),
    ]
