# Generated by Django 6.1.1 on 2026-09-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_card_description_card_name_card_rariry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='rariry',
            new_name='rarity',
        ),
    ]
