# Generated by Django 6.1.1 on 2026-09-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hearts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
