# Generated by Django 6.1.1 on 2026-09-26 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player_hearts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_1_at', models.DateTimeField(blank=True, null=True)),
                ('action_2_at', models.DateTimeField(blank=True, null=True)),
                ('action_3_at', models.DateTimeField(blank=True, null=True)),
                ('action_4_at', models.DateTimeField(blank=True, null=True)),
                ('action_5_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
            options={
                'unique_together': {('player', 'character')},
            },
        ),
    ]
