# Generated by Django 6.1.1 on 2026-09-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_interactioncooldown'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Действие 1'), (2, 'Действие 2'), (3, 'Действие 3'), (4, 'Действие 4'), (5, 'Действие 5')])),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='interactions/')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
            ],
        ),
    ]
