# Generated by Django 6.1.1 on 2026-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_interactionscene'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='spins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
