# Generated by Django 6.1.1 on 2026-09-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
