# Generated by Django 6.1.1 on 2026-09-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='characters',
            field=models.ManyToManyField(blank=True, to='game.character'),
        ),
    ]
