# Generated by Django 6.1.1 on 2026-09-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_player_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='welcome_bonus_received',
            field=models.BooleanField(default=False),
        ),
    ]
